version: '2'

volumes:
  mysql_data_dev: {}
  solr_data_dev: {}

services:

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
    volumes:
      - mysql_data_dev:/var/lib/mysql

  solr:
    image: solr:5.4.1
    ports:
     - "8983:8983"
    volumes:
      - solr_data_dev:/opt/solr/server/solr/mycores
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=orb
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - mysql
